project_id = "ikazuqhukvtdorscoads"

[functions.create-custom-checkout-session]
verify_jwt = false

[functions.get-analytics]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.get-checkout-session]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-customer-portal-session]
verify_jwt = false

[functions.get-admin-clients]
verify_jwt = false

[functions.update-client]
verify_jwt = false

[functions.delete-client]
verify_jwt = false

[functions.create-client]
verify_jwt = false

[functions.generate-checkout-link]
verify_jwt = false

[functions.get-client-profile]
verify_jwt = false

[functions.update-client-status]
verify_jwt = false